version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: staffmanagement_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: staff_management
    ports:
      - "5096:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: staffmanagement_backend
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin123
      PGDATABASE: staff_management
      PGHOST: postgres
      PGPORT: 5432
    ports:
      - "3096:3096"

  hr-staff-ui:
    build: ./HR-Staffmanagement
    container_name: staffmanagement_hr_ui
    ports:
      - "8161:80"
    depends_on:
      - backend

volumes:
  postgres_data:

